version: "3.9"
services:
  dremio_master_coordinator:
    image: dremio/dremio-oss:latest
    ports:
      # Web UI
      - "9047:9047"
      # JDBC / ODBC
      - "31010:31010"
      # Flight
      - "32010:32010"
    volumes:
    # Dremio data
    - ./dremio_data:/opt/dremio/data
    # dremio.conf
    - ./dremio_master_coordinator.conf:/opt/dremio/conf/dremio.conf

  dremio_executor:
    image: dremio/dremio-oss:latest
    volumes:
    # Dremio data
    - ./dremio_data:/opt/dremio/data
    # dremio.conf
    - ./dremio_executor.conf:/opt/dremio/conf/dremio.conf
